name-template: "v$NEXT_MINOR_VERSION ğŸŒˆ"
tag-template: "v$NEXT_MINOR_VERSION"
categories:
  - title: "ğŸš€ Features"
    labels:
      - "ğŸ•¹ ê¸°ëŠ¥"
      - "âš’ ë¦¬íŒ©í† ë§"
      - "ğŸ“±ìœ ì•„ì´"
      - "ğŸ–¥ ì–´ë“œë¯¼"
      - "ğŸ— ì¸í”„ë¼"
  - title: "ğŸ› Bug Fixes"
    labels:
      - "ğŸ ë²„ê·¸"
      - "ğŸš í•«í”½ìŠ¤"
  - title: "âŒ Deprecated"
    labels:
      - "âŒ ì‚¬ìš©ë˜ì§€ì•ŠìŒ"
exclude-labels:
  - "âš™ï¸ ì„¤ì •"
  - "ğŸŒˆ í”„ë¡ íŠ¸"
  - "ğŸ» í…ŒìŠ¤íŠ¸"
  - "ğŸ”¥ ë°±ì—”ë“œ"
  - "ğŸ“‹ ë¬¸ì„œ"
  - "ğŸš¨ ì´ìŠˆ"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
