spring:
  # error type to json
  mvc:
    throw-exception-if-no-handler-found: true
  # admin page
  web:
    resources:
      add-mappings: false
  #profiles
  profiles:
    group:
      "local": "console-logging,http-console-logging"
      "dev": "file-logging,http-file-logging,console-logging,http-console-logging"
      "prod": "file-logging,http-file-logging"
      "test": "console-logging"
    include: oauth, datasource
  # pageSize
  data:
    web:
      pageable:
        one-indexed-parameters: true
  # flyway
  flyway:
    enabled: false
  # multipart data
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 10MB
      max-request-size: 10MB
  # actuator
  application:
    name: jujeol-jujeol
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
