name: front-dev-deploy

# PR 요청에 대해 
on:
  pull_request:
    branches:
      - test/github-action-config    # main 브랜치에서 pr 이벤트가 일어났을 때 실행
    types: closed                    # PR이 closed 됐을 때에만 build 실행 
      
defaults:
  run:
    working-directory: ./frontend    # build steps의 run을 ./frontend 경로에서 실행
    
# 환경변수 설정    
env:
  FRONT_LABEL: 3141723409
  
jobs:
  build:
    # close 이벤트 중 merge일 때만 동작 && label이 [front] 일때만 동작
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.id, 3141723409)
    runs-on: deploy-runner
    steps:        
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build:dev

    - name: Deploy
      run: aws s3 sync --delete ./build s3://jujeol-dev-deploy
